### ISSUE TITLE
add audit rules

### ISSUE THREAD

**Issue by Blisk** [OTRF/Set-AuditRule#1]
I am searching all over the internet how to make multiple audit rules for a folder or to export and than import multiple audit rules for a file or folder.
With script I can make new audit rule but only 1 rule for 1 user I can't do that for 2 rules and 2 users. Old audit rule is always deleted when using script. 
With exporting and importing audit rules that doesn't work.
Is there any soultion for this? Except to do that manually?

**Comment by Cyb3rWard0g** [comment]
Hello @Blisk ! Sorry I missed this issue. 

From a two users per rule, I believe it can be done similar to how I handle the `permissions/rights` applied to each rule right? Can you provide an example manually? I want to make sure I capture all the details of your question. For example, something that I need to update is the `SUCCESS` and `FAILURE`  tags so that we can collect both scenarios per rule.

Regarding two rules at the same time, do you mean how we can do a loop and set or modify a SACL on two rules? 

something like this? : https://github.com/OTRF/Blacksmith/blob/master/resources/scripts/powershell/auditing/Set-SACLs.ps1#L5-L44

**Comment by Blisk** [comment]
Hi
I already solved this problem with set one folder with one audit rules and subfolder with another audit rules and it works.

**Comment by Cyb3rWard0g** [comment]
Nicee!! Thank you for letting me know!

 Is there anything I should update in the main script to make it easier?

**Comment by Blisk** [comment]
sorry I can't tell you. But thank you for making code.
